IF EXISTS(SELECT COUNT(*) FROM SYS.OBJECTS WHERE TYPE = 'P' AND NAME = 'PR_TOTAL_CONTAS_PAGAR')
DROP PROCEDURE PR_TOTAL_CONTAS_PAGAR
GO
CREATE PROCEDURE PR_TOTAL_CONTAS_PAGAR
@DATA_INI DATE,
@DATA_FIM DATE,
@LOJA INT,
@TIPO_DATA INT,   /* 0~>VENCIMENTO(padrão) | 1~>EMISSÃO*/
@PERIODO_DATA INT /* 0~>DATA INICIAL E FINAL PASSADA NO PARÂMETRO
					 1~>TODAS EM ABERTO ATÉ A DATA FINAL PASSARA NO PARÂMETRO */
AS

IF @PERIODO_DATA = 0 BEGIN

	SELECT SUM(SALDO) AS SALDO
	FROM VW_CONTAS_PAGAR
	WHERE CASE
			WHEN @TIPO_DATA = 0 THEN DATA_VENCIMENTO 
			WHEN @TIPO_DATA = 1 THEN DATA_EMISSAO
		  END BETWEEN @DATA_INI AND @DATA_FIM AND
		  LJ_ID = @LOJA

END ELSE BEGIN

	SELECT SUM(SALDO) AS SALDO
	FROM VW_CONTAS_RECEBER
	WHERE LJ_ID = @LOJA
END