IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PR_TOTAL_VENDAS_PERIODO')
DROP PROCEDURE PR_TOTAL_VENDAS_PERIODO
GO

CREATE PROCEDURE PR_TOTAL_VENDAS_PERIODO
@DATA_INICIAL DATE,
@DATA_FINAL DATE
AS

SELECT SUM(TOTAL) AS TOTAL
FROM VW_TOTAL_VENDAS_POR_DIA
WHERE DATA BETWEEN @DATA_INICIAL AND @DATA_FINAL


