IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PR_TOTAL_VENDAS_PERIODO')
DROP PROCEDURE PR_TOTAL_VENDAS_PERIODO
GO

CREATE PROCEDURE PR_TOTAL_VENDAS_PERIODO
@DATA_INICIAL DATE,
@DATA_FINAL DATE
AS

SELECT ISNULL((SUM(CAB.SAI_TOT) - (ISNULL(SAI_VLFR,0) - ISNULL(SAI_ACESSORIAS,0) - 
	   ISNULL(SAI_VLACR,0) - ISNULL(SAI_VLIPI,0) - ISNULL(SAI_VLICMSRT,0))),0) AS TOTAL 
FROM SAI_MT_CAB CAB INNER JOIN CAD_DC DC
	 ON CAB.DC_ID = DC.DC_ID 
WHERE SAI_DT BETWEEN @DATA_INICIAL AND @DATA_FINAL AND 
	  CL_CANC IS NULL AND
	  DC.DC_DV <> 1
GROUP BY SAI_VLFR,SAI_ACESSORIAS,SAI_VLACR, SAI_VLIPI,SAI_VLICMSRT