IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PR_DASH_INFORMACOES_DIARIAS')
DROP PROCEDURE PR_DASH_INFORMACOES_DIARIAS
GO

CREATE PROCEDURE PR_DASH_INFORMACOES_DIARIAS
AS

--SELECT PRINCIPAL QUE RETORNAM TOTAL VENDIDO POR DIA, QUANTIDADE DE PRODUTOS E TICKET MÉDIO
SELECT QUANTIDADE, TOTAL, TICKET FROM

	--RETORNA QUANTIDADE DE PRODUTOS VENDIDOS NO DIA 
	(SELECT ISNULL(CAST(SUM(MAT.DT_QTD) AS DECIMAL(10,2)),0) AS QUANTIDADE
	 FROM SAI_MT_CAB CAB INNER JOIN SAI_MT_MAT MAT 
	 	  ON CAB.SAI_ID = MAT.SAI_ID INNER JOIN CAD_DC DC
		  ON CAB.DC_ID = DC.DC_ID 
	 WHERE SAI_DT = CAST(GETDATE() AS DATE) AND
		   CL_CANC IS NULL AND
		   DC.DC_DV <> 1) AS QUANTIDADE,
	
	--RETORNA O VALOR DE VENDAS NO DIA 
	(SELECT SUM(TOTAL) AS TOTAL 
	 FROM VW_TOTAL_VENDAS_POR_DIA 
	 WHERE DATA = CAST(GETDATE() AS DATE)) AS TOTAL,

	
	--RETORNA O TICKET MÉDIO DAS VENDAS DO DIA 
	(SELECT SUM(TOTAL) / COUNT(*) AS TICKET
	 FROM VW_TOTAL_VENDAS_COM_CUSTO
	 WHERE DATA = CAST(GETDATE() AS DATE)) AS TICKET


				  