IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PR_HISTORICO_12MESES')
DROP PROCEDURE PR_HISTORICO_12MESES
GO

CREATE PROCEDURE PR_HISTORICO_12MESES
AS

-- CRIE A TABELA TEMPORÁRIA
CREATE TABLE #TEMPMESES (
  MES DATE
)

-- PREENCHA A TABELA TEMPORÁRIA COM OS MESES
DECLARE @STARTDATE DATE = DATEADD(MONTH, -13, GETDATE())
DECLARE @ENDDATE DATE = GETDATE()
WHILE @STARTDATE <= @ENDDATE
BEGIN
  INSERT INTO #TEMPMESES (MES) VALUES (@STARTDATE)
  SET @STARTDATE = DATEADD(MONTH, 1, @STARTDATE)
END

DECLARE @DATA_INICIAL DATE
DECLARE @DATA_FINAL DATE
DECLARE @ANO VARCHAR(4)
DECLARE @MES VARCHAR(2)

--PEGA O MÊS ATUAL E O ANO ANTERIOR A DATA DO DIA DA CONSULTA
SET @ANO = (SELECT(YEAR(GETDATE())-1))
SET @MES = (SELECT(MONTH(GETDATE())))

SET @DATA_INICIAL = (SELECT CONVERT(DATE, @ANO+'-'+@MES+'-'+'01', 23))

SET @DATA_FINAL = (SELECT EOMONTH(GETDATE()))

SELECT ISNULL(
		SUM(CASE 
			WHEN  MONTH(DATA) = '' AND YEAR(DATA) = ''
				THEN 0
			ELSE TOTAL 
			END),0) AS TOTAL,
			MONTH(T.MES) AS MES,
			YEAR(T.MES) AS ANO
FROM VW_TOTAL_VENDAS_COM_CUSTO RIGHT JOIN #TEMPMESES T
	ON MONTH(T.MES) = MONTH(DATA) AND
	   YEAR(T.MES) = YEAR(DATA)
WHERE T.MES BETWEEN @DATA_INICIAL AND @DATA_FINAL
GROUP BY YEAR(T.MES), MONTH(T.MES)
ORDER BY YEAR(T.MES), MONTH(T.MES)

-- LIMPE A TABELA TEMPORÁRIA
DROP TABLE #TEMPMESES;