IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PR_CALCULA_LUCRO')
DROP PROCEDURE PR_CALCULA_LUCRO
GO

CREATE PROCEDURE PR_CALCULA_LUCRO
@DATA_INICIO DATE,
@DATA_FINAL DATE
AS

	SELECT (SUM(TOTAL) - SUM(CUSTO)) AS LUCRO 
	FROM 
		(SELECT ISNULL((CAB.SAI_TOT) - (ISNULL(SAI_VLFR,0) - ISNULL(SAI_ACESSORIAS,0) - 
				ISNULL(SAI_VLACR,0) - ISNULL(SAI_VLIPI,0) - ISNULL(SAI_VLICMSRT,0)),0) AS TOTAL,
			   
			   SUM(MAT.SAI_CUST) AS CUSTO,
			   CAB.SAI_DT
		FROM SAI_MT_CAB CAB INNER JOIN SAI_MT_MAT MAT 
			 ON CAB.SAI_ID = MAT.SAI_ID INNER JOIN CAD_DC DC
			 ON CAB.DC_ID = DC.DC_ID
		WHERE CAB.CL_CANC IS NULL AND
			  DC.DC_DV <> 1
		GROUP BY CAB.SAI_TOT, CAB.SAI_DT, SAI_VLFR,SAI_ACESSORIAS,SAI_VLACR, SAI_VLIPI,SAI_VLICMSRT
		) AS VENDAS_CUSTO

	WHERE SAI_DT BETWEEN @DATA_INICIO AND @DATA_FINAL

