IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PR_HISTORICO_12MESES')
DROP PROCEDURE PR_HISTORICO_12MESES
GO

CREATE PROCEDURE PR_HISTORICO_12MESES
AS

DECLARE @DATA_INICIAL DATE
DECLARE @DATA_FINAL DATE
DECLARE @ANO VARCHAR(4)
DECLARE @MES VARCHAR(2)

--PEGA O MÊS ATUAL E O ANO ANTERIOR A DATA DO DIA DA CONSULTA
SET @ANO = (SELECT(YEAR(GETDATE())-1))
SET @MES = (SELECT(MONTH(GETDATE())))

SET @DATA_INICIAL = (SELECT CONVERT(DATE, @ANO+'-'+@MES+'-'+'01', 23))

SET @DATA_FINAL = (SELECT EOMONTH(GETDATE()))

SELECT SUM(TOTAL) AS TOTAL,
	   MONTH(DATA) AS MES,
	   YEAR(DATA) AS ANO
FROM VW_TOTAL_VENDAS_COM_CUSTO
WHERE DATA BETWEEN @DATA_INICIAL AND @DATA_FINAL
GROUP BY YEAR(DATA), MONTH(DATA)
ORDER BY YEAR(DATA), MONTH(DATA)
