IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PR_DASH_INFORMACOES_DIARIAS')
DROP PROCEDURE PR_DASH_INFORMACOES_DIARIAS
GO

CREATE PROCEDURE PR_DASH_INFORMACOES_DIARIAS
AS

--SELECT PRINCIPAL QUE RETORNAM TOTAL VENDIDO POR DIA, QUANTIDADE DE PRODUTOS E TICKET MÉDIO
SELECT QUANTIDADE, TOTAL, TICKET FROM

	--RETORNA QUANTIDADE DE PRODUTOS VENDIDOS NO DIA 
	(SELECT ISNULL(CAST(SUM(MAT.DT_QTD) AS DECIMAL(10,2)),0) AS QUANTIDADE
	 FROM SAI_MT_CAB CAB INNER JOIN SAI_MT_MAT MAT 
	 	  ON CAB.SAI_ID = MAT.SAI_ID INNER JOIN CAD_DC DC
		  ON CAB.DC_ID = DC.DC_ID 
	 WHERE SAI_DT = CAST(GETDATE() AS DATE) AND
		   CL_CANC IS NULL AND
		   DC.DC_DV <> 1) AS QUANTIDADE,
	
	--RETORNA O VALOR DE VENDAS NO DIA 
	 (SELECT ISNULL((SUM(CAB.SAI_TOT) - (ISNULL(SAI_VLFR,0) - ISNULL(SAI_ACESSORIAS,0) - 
			 ISNULL(SAI_VLACR,0) - ISNULL(SAI_VLIPI,0) - ISNULL(SAI_VLICMSRT,0))),0) AS TOTAL 
	  FROM SAI_MT_CAB CAB INNER JOIN CAD_DC DC
		   ON CAB.DC_ID = DC.DC_ID 
	  WHERE SAI_DT = CAST(GETDATE() AS DATE) AND
	  	    CL_CANC IS NULL  AND
		    DC.DC_DV <> 1
	  GROUP BY SAI_VLFR,SAI_ACESSORIAS,SAI_VLACR, SAI_VLIPI,SAI_VLICMSRT) AS VENDAS,
	
	--RETORNA O TICKET MÉDIO DAS VENDAS DO DIA 
	 (SELECT ISNULL((SUM(CAB.SAI_TOT) - (ISNULL(SAI_VLFR,0) - ISNULL(SAI_ACESSORIAS,0) - 
			 ISNULL(SAI_VLACR,0) - ISNULL(SAI_VLIPI,0) - ISNULL(SAI_VLICMSRT,0))),0) 
			 / COUNT(SAI_ID) AS TICKET 
	  FROM SAI_MT_CAB CAB INNER JOIN CAD_DC DC
		   ON CAB.DC_ID = DC.DC_ID 
	  WHERE SAI_DT = CAST(GETDATE() AS DATE) AND
			CL_CANC IS NULL AND
			DC.DC_DV <> 1
	  GROUP BY SAI_VLFR,SAI_ACESSORIAS,SAI_VLACR, SAI_VLIPI,SAI_VLICMSRT) AS TICKET


				  