IF EXISTS(SELECT COUNT(*) FROM SYS.TABLES WHERE TYPE = 'P' AND NAME = 'PR_TOTAL_CONTAS_RECEBER')
DROP PROCEDURE PR_TOTAL_CONTAS_RECEBER
GO
CREATE PROCEDURE PR_TOTAL_CONTAS_RECEBER
@DATA_INI DATE,
@DATA_FIM DATE,
@LOJA INT,
@TIPO_DATA INT,   /*0~>VENCIMENTO(padrão) | 1~>EMISSÃO*/
@PERIODO_DATA INT /* 0~>DATA INICIAL E FINAL PASSADA NO PARÂMETRO
					 1~>TODAS EM ABERTO ATÉ A DATA FINAL PASSARA NO PARÂMETRO */
AS

DECLARE @DOC_NFE INT
DECLARE @DOC_RECEBIDOS INT
SET @DOC_NFE = (SELECT PR_VL FROM TAB_PR WHERE PR_CD = 'PR_DC_PDR_NT_FISCAL')
SET @DOC_RECEBIDOS = (SELECT PR_VL FROM TAB_PR WHERE PR_CD = 'TP_RC_SMP_CR_V2')


IF @PERIODO_DATA = 0 BEGIN

	SELECT SUM(SALDO) AS SALDO
	FROM VW_CONTAS_RECEBER
	WHERE CASE
			WHEN @TIPO_DATA = 0 THEN DATA_VENCIMENTO 
			WHEN @TIPO_DATA = 1 THEN DATA_EMISSAO
		  END BETWEEN @DATA_INI AND @DATA_FIM AND
		  DC_ID IN (@DOC_NFE,@DOC_RECEBIDOS) AND
		  LJ_ID = @LOJA

END ELSE BEGIN

	SELECT SUM(SALDO) AS SALDO
	FROM VW_CONTAS_RECEBER
	WHERE DC_ID IN (@DOC_NFE,@DOC_RECEBIDOS) AND
		  LJ_ID = @LOJA
END