IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PR_HISTORICO_12MESES')
DROP PROCEDURE PR_HISTORICO_12MESES
GO

CREATE PROCEDURE PR_HISTORICO_12MESES
AS

DECLARE @DATA_INICIAL DATE
DECLARE @DATA_FINAL DATE
DECLARE @ANO VARCHAR(4)
DECLARE @MES VARCHAR(2)

--PEGA O MÊS ATUAL E O ANO ANTERIOR A DATA DO DIA DA CONSULTA
SET @ANO = (SELECT(YEAR(GETDATE())-1))
SET @MES = (SELECT(MONTH(GETDATE())))

SET @DATA_INICIAL = (SELECT CONVERT(DATE, @ANO+'-'+@MES+'-'+'01', 23))

SET @DATA_FINAL = (SELECT EOMONTH(GETDATE()))

SELECT ISNULL((SUM(CAB.SAI_TOT) - (ISNULL(SAI_VLFR,0) - ISNULL(SAI_ACESSORIAS,0) - 
	   ISNULL(SAI_VLACR,0) - ISNULL(SAI_VLIPI,0) - ISNULL(SAI_VLICMSRT,0))),0) AS TOTAL,
	   MONTH(SAI_DT) AS MES,
	   YEAR(SAI_DT) AS ANO
FROM SAI_MT_CAB CAB INNER JOIN CAD_DC DC
	 ON CAB.DC_ID = DC.DC_ID 
WHERE SAI_DT BETWEEN @DATA_INICIAL AND @DATA_FINAL AND 
	  CL_CANC IS NULL AND
	  DC.DC_DV <> 1
GROUP BY SAI_VLFR,SAI_ACESSORIAS,SAI_VLACR, SAI_VLIPI,SAI_VLICMSRT, YEAR(SAI_DT), MONTH(SAI_DT)
ORDER BY YEAR(SAI_DT), MONTH(SAI_DT)
