IF EXISTS (SELECT * FROM SYS.ALL_VIEWS WHERE TYPE = 'V' AND NAME = 'VW_METAS_LOJA')
DROP VIEW VW_METAS_LOJA
GO

CREATE VIEW VW_METAS_LOJA 
AS

SELECT META_VALOR AS META,
	   META_VALOR_SUPER AS SUPER_META,
	   META_MES AS MES,
	   META_ANO AS ANO,
	   LJ_ID AS LOJA
FROM META_LOJA



