IF EXISTS (SELECT * FROM SYS.all_views WHERE TYPE = 'V' AND NAME = 'VW_TOTAL_VENDAS_COM_CUSTO')
DROP VIEW VW_TOTAL_VENDAS_COM_CUSTO
GO
CREATE VIEW VW_TOTAL_VENDAS_COM_CUSTO
AS

SELECT ISNULL((SUM(CAB.SAI_TOT) - 
		(ISNULL(SAI_VLFR,0) - ISNULL(SAI_ACESSORIAS,0) - 
		 ISNULL(SAI_VLACR,0) - ISNULL(SAI_VLIPI,0) - 
		 ISNULL(SAI_VLICMSRT,0))
		),0) AS TOTAL,
	   (SELECT SUM(ISNULL(SAI_CUST,0))FROM SAI_MT_MAT WHERE SAI_ID = CAB.SAI_ID) AS CUSTO,
	   CAB.SAI_DT AS DATA
FROM SAI_MT_CAB CAB INNER JOIN CAD_DC DC
		ON CAB.DC_ID = DC.DC_ID LEFT JOIN NF_STATUS NFS
		ON CAB.SAI_ID = NFS.SAI_ID
WHERE CAB.CL_CANC IS NULL AND
	  DC.DC_DV <> 1 AND
	  CAB.SAI_ORG = 'NFE' AND
	  NFS.STA_ST IN ('NFE')
GROUP BY CAB.SAI_DT, SAI_VLFR,
		 SAI_ACESSORIAS, SAI_VLACR,
		 SAI_VLIPI, SAI_VLICMSRT, CAB.SAI_ID


UNION ALL

SELECT ISNULL((SUM(CAB.SAI_TOT) - 
		(ISNULL(SAI_VLFR,0) - ISNULL(SAI_ACESSORIAS,0) - 
		 ISNULL(SAI_VLACR,0) - ISNULL(SAI_VLIPI,0) - 
		 ISNULL(SAI_VLICMSRT,0))
		),0) AS TOTAL,
	   (SELECT SUM(ISNULL(SAI_CUST,0))FROM SAI_MT_MAT WHERE SAI_ID = CAB.SAI_ID) AS CUSTO,
	   CAB.SAI_DT AS DATA
FROM SAI_MT_CAB CAB INNER JOIN CAD_DC DC
		ON CAB.DC_ID = DC.DC_ID LEFT JOIN NF_STATUS NFS
		ON CAB.SAI_ID = NFS.SAI_ID
WHERE CAB.CL_CANC IS NULL AND
	  DC.DC_DV <> 1 AND
	  CAB.SAI_ORG = 'NFCE' 
GROUP BY CAB.SAI_DT, SAI_VLFR,
		 SAI_ACESSORIAS, SAI_VLACR, 
		 SAI_VLIPI, SAI_VLICMSRT, CAB.SAI_ID
