CREATE VIEW VW_METAS_LOJA 
AS


SELECT MAX(MDT_METAREAL1) AS META,
	   MAX(MDT_METAREAL2) AS SUPER_META,
	   MDT_MES AS MES,
	   MDT_ANO AS ANO,
	   LJ_ID AS LOJA
FROM TAB_MDT
GROUP BY MDT_MES, MDT_ANO, LJ_ID



