IF EXISTS (SELECT * FROM sys.all_views WHERE type = 'V' AND name = 'VW_TOTAL_VENDAS_POR_DIA')
DROP VIEW VW_TOTAL_VENDAS_POR_DIA
GO
CREATE VIEW VW_TOTAL_VENDAS_POR_DIA
AS

--SOMA SÓ NFE SE FOR VALIDADA
SELECT ISNULL((SUM(CAB.SAI_TOT) - (ISNULL(SAI_VLFR,0) - ISNULL(SAI_ACESSORIAS,0) - 
	   ISNULL(SAI_VLACR,0) - ISNULL(SAI_VLIPI,0) - ISNULL(SAI_VLICMSRT,0))),0) 
	   AS TOTAL,
	   SAI_ORG AS MODELO,
	   SAI_DT AS DATA
FROM SAI_MT_CAB CAB INNER JOIN CAD_DC DC
	 ON CAB.DC_ID = DC.DC_ID LEFT JOIN NF_STATUS NFS
	 ON CAB.SAI_ID = NFS.SAI_ID
WHERE CL_CANC IS NULL AND
	  DC.DC_DV <> 1 AND
	  CAB.SAI_ORG = 'NFE' AND
	  NFS.STA_ST IN ('NFE')
GROUP BY SAI_VLFR,SAI_ACESSORIAS,SAI_VLACR,
		 SAI_VLIPI,SAI_VLICMSRT, SAI_ORG,
		 SAI_DT,STA_ST

UNION

--SOMA OS VALORES DE NFC-E (SEJAM FISCAIS OU ORÇAMENTOS)
SELECT ISNULL((SUM(CAB.SAI_TOT) - (ISNULL(SAI_VLFR,0) - ISNULL(SAI_ACESSORIAS,0) - 
	   ISNULL(SAI_VLACR,0) - ISNULL(SAI_VLIPI,0) - ISNULL(SAI_VLICMSRT,0))),0)
	   AS TOTAL,
	   SAI_ORG AS MODELO,
	   SAI_DT AS DATA
FROM SAI_MT_CAB CAB INNER JOIN CAD_DC DC
	 ON CAB.DC_ID = DC.DC_ID LEFT JOIN NF_STATUS NFS
	 ON CAB.SAI_ID = NFS.SAI_ID
WHERE CL_CANC IS NULL AND
	  DC.DC_DV <> 1 AND
	  CAB.SAI_ORG = 'NFCE'
GROUP BY SAI_VLFR,SAI_ACESSORIAS,SAI_VLACR,
		 SAI_VLIPI,SAI_VLICMSRT, SAI_ORG,
		 SAI_DT,STA_ST
