IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PRD_INFO_VENDEDORES')
DROP PROCEDURE PRD_INFO_VENDEDORES
GO
CREATE PROCEDURE PRD_INFO_VENDEDORES
@DATA_INICIAL DATE,
@DATA_FINAL DATE
AS

WITH CTE_QUANTIDADE AS( --CTE PARA PEGAR A QUANTIDADE DE VENDAS DE CADA VENDEDOR
SELECT COUNT(CODIGO_VENDEDOR) AS QTD,CODIGO_VENDEDOR
FROM VW_DASH_VENDEDORES
WHERE DATA_VENDA BETWEEN @DATA_INICIAL AND @DATA_FINAL
GROUP BY CODIGO_VENDEDOR
),

CTE_TOTAL AS( --CTE PARA PEGAR O TOTAL DE VENDAS DE CADA VENDEDOR
SELECT SUM(TOTAL_VENDA) AS TOTAL,CODIGO_VENDEDOR
FROM VW_DASH_VENDEDORES
WHERE DATA_VENDA BETWEEN @DATA_INICIAL AND @DATA_FINAL
GROUP BY CODIGO_VENDEDOR
),

CTE_METAS AS( --CTE PARA PEGAR O TOTAL DE VENDAS DE CADA VENDEDOR
SELECT SUM(ISNULL(META_VALOR,0)) AS META,
	   SUM(ISNULL(META_VALOR_SUPER,0)) AS SUPER_META,
	   CL_ID
FROM META_VENDEDORES
WHERE (META_MES BETWEEN MONTH(@DATA_INICIAL) AND MONTH(@DATA_FINAL) AND
	   META_ANO BETWEEN YEAR(@DATA_INICIAL) AND YEAR(@DATA_FINAL))
GROUP BY CL_ID
)

SELECT SUM(TOTAL_VENDA) AS TOTAL,
	   VW.CODIGO_VENDEDOR,
	   VENDEDOR,
	   CAST((TOTAL.TOTAL / QTD.QTD)AS DECIMAL(10,2)) AS TICKET,
	   META,
	   SUPER_META
FROM VW_DASH_VENDEDORES VW INNER JOIN CTE_QUANTIDADE QTD
	 ON VW.CODIGO_VENDEDOR = QTD.CODIGO_VENDEDOR INNER JOIN CTE_TOTAL TOTAL
	 ON VW.CODIGO_VENDEDOR = TOTAL.CODIGO_VENDEDOR LEFT JOIN CTE_METAS 
	 ON VW.CODIGO_VENDEDOR = CTE_METAS.CL_ID
WHERE DATA_VENDA BETWEEN @DATA_INICIAL AND @DATA_FINAL
GROUP BY VENDEDOR, VW.CODIGO_VENDEDOR, TOTAL.TOTAL, QTD.QTD,META,SUPER_META
ORDER BY TOTAL DESC

