IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PRD_INFORMACOES_DIARIAS_VENDEDOR')
DROP PROCEDURE PRD_INFORMACOES_DIARIAS_VENDEDOR
GO

CREATE PROCEDURE PRD_INFORMACOES_DIARIAS_VENDEDOR
@COD_VENDEDOR INT
AS

--SELECT PRINCIPAL QUE RETORNAM TOTAL VENDIDO POR DIA, QUANTIDADE DE PRODUTOS E TICKET MÉDIO
SELECT QUANTIDADE, TOTAL, TICKET FROM

	--RETORNA QUANTIDADE DE PRODUTOS VENDIDOS NO DIA 
	(SELECT ISNULL(CAST(SUM(MAT.DT_QTD) AS DECIMAL(10,2)),0) AS QUANTIDADE
	 FROM SAI_MT_CAB CAB INNER JOIN SAI_MT_MAT MAT 
	 	  ON CAB.SAI_ID = MAT.SAI_ID INNER JOIN CAD_DC DC
		  ON CAB.DC_ID = DC.DC_ID 
	 WHERE SAI_DT = CAST(GETDATE() AS DATE) AND
		   CL_CANC IS NULL AND
		   CAB.CL_ID = @COD_VENDEDOR AND
		   DC.DC_DV <> 1) AS QUANTIDADE,
	
	--RETORNA O VALOR DE VENDAS NO DIA 
	(SELECT SUM(TOTAL_VENDA) AS TOTAL 
	 FROM VW_DASH_VENDEDORES 
	 WHERE DATA_VENDA = CAST(GETDATE() AS DATE) AND
		   CODIGO_VENDEDOR = @COD_VENDEDOR) AS TOTAL,

	
	--RETORNA O TICKET MÉDIO DAS VENDAS DO DIA 
	(SELECT SUM(TOTAL_VENDA) / COUNT(*) AS TICKET
	 FROM VW_DASH_VENDEDORES
	 WHERE DATA_VENDA = CAST(GETDATE() AS DATE)AND
		   CODIGO_VENDEDOR = @COD_VENDEDOR) AS TICKET
  