IF EXISTS (SELECT * FROM sys.objects WHERE type = 'V' AND name = 'VW_DASH_VENDEDORES')
DROP VIEW VW_DASH_VENDEDORES
GO
CREATE VIEW VW_DASH_VENDEDORES
AS

SELECT SAI_TOT AS TOTAL_VENDA,
	   CL.CL_NOME AS VENDEDOR,
	   CL.CL_ID AS CODIGO_VENDEDOR,
	   CAB.SAI_DT AS DATA_VENDA
FROM SAI_MT_CAB CAB INNER JOIN CAD_CL CL
	 ON CAB.CL_ID = CL.CL_ID INNER JOIN CAD_DC DC
	 ON CAB.DC_ID = DC.DC_ID
WHERE CAB.CL_CANC IS NULL AND
	  DC.DC_DV <> 1